// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOicjfGqkB5pZrL4youOzH8IS0BNWROW0',
    appId: '1:43814722866:web:cc22a60cc285edddcc8b2b',
    messagingSenderId: '43814722866',
    projectId: 'esp3-9a8c9',
    authDomain: 'esp3-9a8c9.firebaseapp.com',
    databaseURL: 'https://esp3-9a8c9-default-rtdb.firebaseio.com',
    storageBucket: 'esp3-9a8c9.firebasestorage.app',
    measurementId: 'G-6K4XYEPME1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3f6C5_bquSDt9-Doi5DmQaL0N-sXbAKo',
    appId: '1:43814722866:android:d3b5063e0ac6ff0dcc8b2b',
    messagingSenderId: '43814722866',
    projectId: 'esp3-9a8c9',
    databaseURL: 'https://esp3-9a8c9-default-rtdb.firebaseio.com',
    storageBucket: 'esp3-9a8c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCdrFx59i5EkXoW72CZD2q3lpFwdtgZko',
    appId: '1:43814722866:ios:4ef5587931ea487bcc8b2b',
    messagingSenderId: '43814722866',
    projectId: 'esp3-9a8c9',
    databaseURL: 'https://esp3-9a8c9-default-rtdb.firebaseio.com',
    storageBucket: 'esp3-9a8c9.firebasestorage.app',
    iosClientId: '43814722866-cjmf97rfdgva3kugh9meg7jth1o0ia4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCdrFx59i5EkXoW72CZD2q3lpFwdtgZko',
    appId: '1:43814722866:ios:4ef5587931ea487bcc8b2b',
    messagingSenderId: '43814722866',
    projectId: 'esp3-9a8c9',
    databaseURL: 'https://esp3-9a8c9-default-rtdb.firebaseio.com',
    storageBucket: 'esp3-9a8c9.firebasestorage.app',
    iosClientId: '43814722866-cjmf97rfdgva3kugh9meg7jth1o0ia4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOicjfGqkB5pZrL4youOzH8IS0BNWROW0',
    appId: '1:43814722866:web:7d98a18140e08b77cc8b2b',
    messagingSenderId: '43814722866',
    projectId: 'esp3-9a8c9',
    authDomain: 'esp3-9a8c9.firebaseapp.com',
    databaseURL: 'https://esp3-9a8c9-default-rtdb.firebaseio.com',
    storageBucket: 'esp3-9a8c9.firebasestorage.app',
    measurementId: 'G-Y11X79Q4F1',
  );
}
